name: Hexo Deploy

on:
  push:

jobs:
  hexo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "a-mask-man"
          git config --global user.email "mask@mask.com"
          sed -i "s/__GITHUB_TOKEN__/${GITHUB_TOKEN}/" _config.yml
      - name: NPM Install
        run: npm install
      - name: Hexo Clean
        run: ./node_modules/.bin/hexo clean
      - name: Hexo Generate
        run: ./node_modules/.bin/hexo g
      - name: Hexo Deploy
        run: ./node_modules/.bin/hexo d

      


